#!/bin/bash

#Submit this script with: sbatch thefilename


#SBATCH -J "LosForces"   # job name
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=5
#SBATCH --time=01:30:00
#SBATCH --mem=10G

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load cuda/11.2 openmpi/4.1.1_cuda-11.2


#./run_1_and_2_decompose_and_database.sh
./run_3_only_xspecfem.sh

# add more time when saving more stations (~ 30 min more)


# to reserve nodes in debugging
#srun --pty -t 12:00:00  --gres=gpu:2  -n 10 /bin/bash -l
